import { ProgressIndicator } from '../ProgressIndicator/ProgressIndicator';
import { Box } from '../Box/Box';
import { StyledMainContainer } from './MainContainer.styled';
import img from '../../images/tileable-doodle.png';
import { useMedia } from 'react-use';

import Head from 'next/head';

export const MainContainer = ({ children }) => {
  const isMobie = useMedia('(min-width: 1024px)');

  return (
    <StyledMainContainer>
      <Head>
        <title>Chad Store</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isMobie && <ProgressIndicator />}

      <Box
        display="flex"
        alignItems="center"
        justifyContent="center"
        minHeight="100%"
        flexGrow={2}
        backgroundImage={`url("${img.src}")`}
      >
        {children}
      </Box>
    </StyledMainContainer>
  );
};
