import { ProgressIndicator } from '../ProgressIndicator/ProgressIndicator';
import { Box } from '../Box/Box';
import { StyledMainContainer } from './MainContainer.styled';
import img from '../../images/tileable-doodle.png';
import Head from 'next/head';

export const MainContainer = ({ children }) => {
  return (
    <StyledMainContainer>
      <Head>
        <title>Chad Store</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Raleway:wght@700&family=Roboto:wght@400;500;700;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <ProgressIndicator />

      <Box
        display="flex"
        alignItems="center"
        justifyContent="center"
        minHeight="100%"
        flexGrow={2}
        backgroundImage={`url("${img.src}")`}
      >
        {children}
      </Box>
    </StyledMainContainer>
  );
};
