import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { MainContainer } from '../components/MainContainer/MainContainer';
import { Wellcome } from '../components/Wellcome/Wellcome';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chad Store</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MainContainer>
          <Wellcome />
        </MainContainer>
      </main>
    </div>
  );
}
